language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database authors_prime;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install -r requirements.txt
  - pip install coverage
 
script:
  - python manage.py test
notifications:
  slack: andela:vasKtyE0HR7gacZ27GXkiVLD